### ISSUE TITLE
Grinder GUI

### ISSUE THREAD

**Issue by buddyvv** [buddyvv/Sambucus#3]
We need a GUI for the grinder. File type should be a .png .

**Comment by Tylerun** [comment]
How many inputs how many outputs.

**Comment by Tylerun** [comment]
![meatgrindergui](https://user-images.githubusercontent.com/29389193/34576833-d67dfb7c-f144-11e7-9887-dea35eff4709.png)

**Comment by Tylerun** [comment]
Assign me to stuff and it will get done the issue system works well for this.
